### ISSUE TITLE
Clicking tab link does not do anything

### ISSUE THREAD

**Issue by timlaughlin** [skttl/umbraco-matryoshka#30]
Umbraco 8.6.4

Cleared cache, restarted Umbraco, bumped client dependencies.

Packages:

Umbraco Forms
Diplo God Mode
Matryoshka 0.4.0

Rolled back to version 0.2.0 and functionality returned.

**Comment by skttl** [comment]
Any console errors?

**Comment by timlaughlin** [comment]
No. There looks to be too much space on the tabs as well. 

![image](https://user-images.githubusercontent.com/8093200/92024144-60174f00-ed23-11ea-9178-c5b42016f8f5.png)

**Comment by timlaughlin** [comment]
For reference version 0.2.0 works and looks correct.

![image](https://user-images.githubusercontent.com/8093200/92024376-c00df580-ed23-11ea-9cbf-caccb80b05cb.png)

**Comment by skttl** [comment]
Hi @timlaughlin 

Just tried a fresh 8.6.4 with Forms and God Mode installed, and it worked just as expected.

I must admit, I just used the latest source of Matryoshka, so maybe one of the 3 commits since 0.4.0 has fixed it.

I'm planning on getting 0.5.0 out in a short time, so you should try upgrading then :)
